"""
Cricket Pose Analyzer AI - Master Pipeline Orchestrator
======================================================
Coordinates end-to-end processing pipeline from raw video input to annotated
video output, biomechanical metrics, charts, spatial heatmaps, coaching reports,
data exports (CSV/JSON), and single-click ZIP archive creation.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

from cricket_pose_ai.coaching_engine import CoachingReport, RuleBasedCoachingEngine
from cricket_pose_ai.config import FRAMES_DIR, GRAPHS_DIR, HEATMAPS_DIR, OUTPUT_DIR
from cricket_pose_ai.heatmap_generator import MotionHeatmapGenerator
from cricket_pose_ai.motion_analyzer import MotionAnalyzer, MotionSummaryMetrics
from cricket_pose_ai.report_generator import PDFReportGenerator
from cricket_pose_ai.session_manager import SessionManager, SessionRecord
from cricket_pose_ai.utils import (
    create_analysis_zip,
    export_to_csv,
    export_to_json,
    setup_logger,
)
from cricket_pose_ai.video_processor import VideoMetadata, VideoProcessor
from cricket_pose_ai.visualizer import PoseVisualizer

logger = setup_logger("CricketPoseAI.Analyzer")


@dataclass
class FullAnalysisOutput:
    """Container for all artifacts generated by the analysis pipeline."""
    video_metadata: VideoMetadata
    summary: MotionSummaryMetrics
    coaching: CoachingReport
    framewise_records: List[Dict[str, Any]]
    processed_video_path: Path
    side_by_side_video_path: Path
    pdf_report_path: Path
    csv_path: Path
    json_path: Path
    zip_path: Path
    graph_paths: Dict[str, Path]
    heatmap_paths: Dict[str, Path]
    session_record: SessionRecord


class CricketPoseAnalyzer:
    """Master orchestration engine for Cricket Pose Analyzer AI."""

    def __init__(self):
        self.video_processor = VideoProcessor()
        self.heatmap_generator = MotionHeatmapGenerator()
        self.coaching_engine = RuleBasedCoachingEngine()
        self.visualizer = PoseVisualizer()
        self.pdf_generator = PDFReportGenerator()
        self.session_manager = SessionManager()

    def analyze_video(
        self,
        video_path: Path,
        progress_callback: Optional[Callable[[float, str], None]] = None
    ) -> FullAnalysisOutput:
        """Runs complete video analysis pipeline end-to-end."""

        logger.info(f"Starting full analysis pipeline for video: {video_path}")

        if progress_callback:
            progress_callback(0.05, "Initializing video reader & pose model...")

        # 1. Output file destinations
        processed_mp4 = OUTPUT_DIR / "processed_video.mp4"
        side_by_side_mp4 = OUTPUT_DIR / "side_by_side_video.mp4"
        pdf_path = OUTPUT_DIR / "analysis_report.pdf"
        csv_path = OUTPUT_DIR / "joint_angles.csv"
        json_path = OUTPUT_DIR / "metrics.json"
        zip_path = OUTPUT_DIR / "analysis.zip"

        # 2. Process video frame sequence
        biomech_list, landmarks_hist, bat_hist, metadata, bg_frame = self.video_processor.process_video_sequence(
            video_path=video_path,
            output_video_path=processed_mp4,
            side_by_side_path=side_by_side_mp4,
            progress_callback=lambda pct, msg: progress_callback(0.05 + pct * 0.50, msg) if progress_callback else None
        )

        if progress_callback:
            progress_callback(0.60, "Computing kinetic profiles & shot phase segmentation...")

        # 3. Kinematic Sequence & Shot Phase Analysis
        motion_analyzer = MotionAnalyzer(fps=metadata.fps)
        records, summary = motion_analyzer.analyze_full_sequence(
            biomechanics_list=biomech_list,
            landmarks_history=landmarks_hist,
            bat_history=bat_hist,
            img_w=metadata.width,
            img_h=metadata.height
        )

        if progress_callback:
            progress_callback(0.70, "Evaluating rule-based AI coaching engine...")

        # 4. Coaching Engine Evaluation
        coaching = self.coaching_engine.evaluate_performance(summary)

        if progress_callback:
            progress_callback(0.78, "Generating spatial motion heatmaps...")

        # 5. Spatial Motion Heatmaps
        wrist_pts = [(r["head_x"], r["head_y"]) for r in records]  # fallback
        if landmarks_hist:
            wrist_pts = [(lms["RIGHT_WRIST"].px, lms["RIGHT_WRIST"].py) for lms in landmarks_hist if lms and "RIGHT_WRIST" in lms]

        bat_pts = [b.bat_tip for b in bat_hist if b.detected]
        head_pts = [(r["head_x"], r["head_y"]) for r in records]
        foot_pts = [(lms["LEFT_ANKLE"].px, lms["LEFT_ANKLE"].py) for lms in landmarks_hist if lms and "LEFT_ANKLE" in lms]
        com_pts = [(r["com_x"], r["com_y"]) for r in records]

        heatmap_paths = self.heatmap_generator.generate_all_heatmaps(
            wrist_pts=wrist_pts,
            bat_pts=bat_pts,
            head_pts=head_pts,
            foot_pts=foot_pts,
            com_pts=com_pts,
            img_w=metadata.width,
            img_h=metadata.height,
            background_frame=bg_frame
        )

        if progress_callback:
            progress_callback(0.85, "Rendering analytical graphs & charts...")

        # 6. Analytics Graphs Generation
        graph_paths = self.visualizer.generate_analytics_charts(records, GRAPHS_DIR)

        if progress_callback:
            progress_callback(0.90, "Compiling PDF report & data exports...")

        # 7. Data Exports (CSV & JSON)
        export_to_csv(records, csv_path)

        json_payload = {
            "metadata": {
                "video_name": video_path.name,
                "fps": metadata.fps,
                "total_frames": metadata.total_frames,
                "duration_sec": metadata.duration_sec
            },
            "summary_metrics": {
                "overall_technique_score": summary.overall_technique_score,
                "balance_index": summary.balance_index,
                "head_stability_index": summary.head_stability_index,
                "weight_transfer_index": summary.weight_transfer_index,
                "max_bat_speed_px": summary.max_bat_speed_px,
                "max_spine_lean_deg": summary.max_spine_lean_deg
            },
            "coaching_report": {
                "grade": coaching.technique_grade,
                "verdict": coaching.summary_verdict,
                "strengths": coaching.strengths,
                "weaknesses": coaching.weaknesses,
                "drills": coaching.recommended_drills
            }
        }
        export_to_json(json_payload, json_path)

        # 8. PDF Report Generation
        self.pdf_generator.generate_single_report(
            summary=summary,
            coaching=coaching,
            graph_paths=graph_paths,
            heatmap_paths=heatmap_paths,
            pdf_filename="analysis_report.pdf"
        )

        # 9. Session History Record
        sess_record = self.session_manager.save_session(
            video_name=video_path.name,
            summary=summary,
            grade=coaching.technique_grade,
            artifacts_dir=str(OUTPUT_DIR)
        )

        # 10. Single-click ZIP Bundle Creation
        create_analysis_zip(zip_path)

        if progress_callback:
            progress_callback(1.0, "Analysis complete! All artifacts generated.")

        logger.info(f"Full analysis completed successfully for {video_path.name}")

        return FullAnalysisOutput(
            video_metadata=metadata,
            summary=summary,
            coaching=coaching,
            framewise_records=records,
            processed_video_path=processed_mp4,
            side_by_side_video_path=side_by_side_mp4,
            pdf_report_path=pdf_path,
            csv_path=csv_path,
            json_path=json_path,
            zip_path=zip_path,
            graph_paths=graph_paths,
            heatmap_paths=heatmap_paths,
            session_record=sess_record
        )
